### ISSUE TITLE
Draw a circle and a text produce strange result (black line)

### ISSUE THREAD

**Issue by LaurentPlagne** [GiovineItalia/Compose.jl#292] opened 2018-08-29 06:45 UTC
The following code produces a black line between the circle and the text when I add the stroke("black") to draw a line around the circle:
```julia
c=compose(context(),circle(0.5,0.5,0.3),fill("red"),stroke("black"))
t=compose(context(),text(0.2,0.2,"toto"),fill("black"))

img=compose(context(),c,t)
draw(PDF("toto.pdf",6cm,6cm), img)
```

The line disappears when drawing the text first then the circle.
Is it a bug or a feature ?
(tested with Julia 6.2 and 6.4)

**Comment by bjarthur** [comment] 2018-08-29 11:33
i can reproduce.  clearly a bug.  doesn't happen with SVG.

**Comment by LaurentPlagne** [comment] 2018-08-29 12:00
Thank you very much ! I can export to SVG.

**Comment by LaurentPlagne** [comment] 2018-09-03 15:47
Is there any chance for this bug to be addressed soon ? Because, using the SVG backend, I have problems with the fonts coloring and rendering... I should take a look at it myself but I know very little about Cairo and graphics in general.

**Comment by Mattriks** [comment] 2018-09-04 04:03
These examples might help diagnose the issue:
```julia
# Circle and text are child nodes, and text follows circle: line appears 
img1 = compose(context(),
        (context(), circle(0.5,0.5,0.2), fill("red"), stroke("black")),
        (context(), text(0.2,0.2,"toto"), fill("black"))
)

# Circle is in parent node: works
img2 = compose(context(),
        circle(0.5,0.5,0.2), fill("red"), stroke("black"),
        (context(), text(0.2,0.2,"toto"), fill("black"))
)

# Another node between circle and text: works
img3 = compose(context(),
        (context(), circle(0.5,0.5,0.2), fill("red"), stroke("black")),
        (context(), rectangle(0.4, 0.7, 0.2, 0.2), stroke("black"), fill("white")),
        (context(), text(0.2,0.2,"toto"), fill("black"))
)

draw(PNG("issue292a.png",9cm,3cm), hstack(img1,img2,img3))
```
![issue292a](https://user-images.githubusercontent.com/18226881/45009276-7dd54f00-b04a-11e8-860e-b68f5afd505f.png)

**Comment by lobingera** [comment] 2018-09-04 07:43
I have some background on libcairo and the 'bug' looks like the path of the circle is not correctly closed, so it's connected to the text in the next drawing step.

**Comment by LaurentPlagne** [comment] 2018-09-04 08:42
Thank you for these additional tests. I think that most of problems disappear without the stroke command.
BTW the hstack keyword is nice ! I did not find it in the documentation...

Here is the kind of drawing I am playing with (on which you can notice some transient piece of black lines on the right of some nodes...) 
 
![out](https://user-images.githubusercontent.com/24976886/45020220-9fc0d880-b02e-11e8-9b13-3afa95426a56.gif)

**Comment by bjarthur** [comment] 2018-09-04 11:14
relevant code is [here](https://github.com/GiovineItalia/Compose.jl/blob/master/src/cairo_backends.jl#L502)

**Comment by lobingera** [comment] 2018-09-04 11:39
Yes, Cairo.circle is pointing to Graphics.circle which adds an arc (full circle) to the current path. But doesn't closepath.

**Comment by Mattriks** [comment] 2018-09-04 15:47
Ellipse (which also uses `arc`) has the same behaviour:
```julia
img1 = compose(context(),
        (context(), ellipse(0.5,0.5,0.3,0.15), fill("red"), stroke("black")),
        (context(), text(0.2,0.2,"toto"), fill("black"))
)

img2 = compose(context(),
        ellipse(0.5,0.5,0.3,0.15), fill("red"), stroke("black"),
        (context(), text(0.2,0.2,"toto"), fill("black"))
)

img3 = compose(context(),
        (context(), ellipse(0.5,0.5,0.3,0.15), fill("red"), stroke("black")),
        (context(), rectangle(0.4, 0.65, 0.2, 0.2), stroke("black"), fill("white")),
        (context(), text(0.2,0.2,"toto"), fill("black"))
)
hstack(img1,img2,img3)
```
![issue292b](https://user-images.githubusercontent.com/18226881/45042204-8612a600-b0ad-11e8-8864-5233686127d7.png)

**Comment by Mattriks** [comment] 2018-09-05 00:48
I don't think closing the `arc` is the issue: instead the line seems to occur when the `arc` is opened.  In this example I use `context(order=)`: 
```julia
img1 = compose(context(),
        (context(order=1), ellipse(0.5,0.5,0.3,0.15), fill("red"), stroke("black")),
        (context(order=2), text(0.2,0.2,"toto"), fill("black"))
)

img2 = compose(context(),
        (context(order=2), ellipse(0.5,0.5,0.3,0.15), fill("red"), stroke("black")),
        (context(order=1), text(0.2,0.2,"toto"), fill("black"))
)
draw(PNG("issue292c.png",9cm,3cm), hstack(img1, img2))
```  
![issue292c](https://user-images.githubusercontent.com/18226881/45064575-0100ae80-b0f8-11e8-9cb2-4d720eb89147.png)
The [cairo docs](https://www.cairographics.org/manual/cairo-Paths.html#cairo-arc) mention this:
"If there is a current point, an initial line segment will be added to the path to connect the current point to the beginning of the arc. If this initial line is undesired, it can be avoided by calling cairo_new_sub_path() before calling cairo_arc()."

`Compose` currently doesn't call a `new_sub_path`, so the next step here is to try that.

**Comment by LaurentPlagne** [comment] 2018-09-05 06:06
I didn't knew about this order argument for context nor the hstack command... Is there an hidden documentation for Compose.jl ?

**Comment by LaurentPlagne** [comment] 2018-09-05 07:07
Thanks !

**Comment by Mattriks** [comment] 2018-09-05 11:38
I added and tested a `new_sub_path` function, which solves the issue. 
Should I wait til #282 has been merged before opening a PR?

**Comment by LaurentPlagne** [comment] 2018-09-05 12:35
Great ! Is it possible to get the correction for a local installation before the PR is take into account ?

**Comment by lobingera** [comment] 2018-09-05 13:35
If a PR exist, you can pull it into your local git repository. https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by tlnagy** [comment] 2018-09-05 17:52
> Should I wait til #282 has been merged before opening a PR? 

At this point, yes.

**Closed** 2018-09-08 18:27 UTC
